var id_names = [{"id":0,"District":"Kailahun"},
{"id":1,"District":"Kenema"},
{"id":2,"District":"Kono"},
{"id":3,"District":"Bombali"},
{"id":4,"District":"Kambia"},
{"id":5,"District":"Koinadugu"},
{"id":6,"District":"Port Loko"},
{"id":7,"District":"Tonkolili"},
{"id":8,"District":"Bo"},
{"id":9,"District":"Bonthe"},
{"id":10,"District":"Moyamba"},
{"id":11,"District":"Pujehun"},
{"id":12,"District":"Western Area"},
{"id":13,"District":"Western Area"}]